### ISSUE TITLE
Spectogram images are not uploading in unit ans ordination windows

### ISSUE THREAD

**Issue by Alem21** [fzyukio/koe#11]
First of all - thank you for this wonderful program, it is very useful and beautifully build!

The issue that I have is that  spectograms are shown during recording separation and whole song table nicely, but as soon as it goes with separate units only handful of them can be seen. I tried different internet connections, computers and browsers but so far did not find a solution.

**Comment by BirdGuyWes** [comment]
Thanks for documenting this - we are aware of the issue and will fix ASAP

**Comment by BirdGuyWes** [comment]
We believe this is now resolved. Get in touch if not!

**Comment by Dumetorum** [comment]
I got a similar issue. I uploaded a new file and imported selections from Raven. I can see the spectrogram in the "Split a song into units" window but when I want to go to "Ordination", "Exemplars" or "Unit table" the spectrograms of selected syllables do not load.
