### ISSUE TITLE
Songs are not viewed in only one of the databases (just blank space,  the contrast scroll is not shown as well) anymore even if the unit table is perfectly normal

### ISSUE THREAD

**Issue by Alem21** [fzyukio/koe#13]

**Comment by BirdGuyWes** [comment]
Hi Alem21 -- sorry to hear you are experiencing issues. Please give us all the details you can to help us reproduce the problem. Cheers!

**Comment by Alem21** [comment]
I am sorry, I do not know how to reproduce the problem, it is just happened after one of log ins. I can provide you with my login and password if you want to see how it looks like(these goes for both issues)

**Comment by BirdGuyWes** [comment]
If you're on Facebook, find the Koe Facebook page (@KoeSoftware) and message us there. We will be happy to help

**Comment by BirdGuyWes** [comment]
This issue was solved by doing a clear cache and hard reload in the users browser.
