### ISSUE TITLE
Spectrograms do not refresh after selection modification

### ISSUE THREAD

**Issue by Dumetorum** [fzyukio/koe#16]
Hello,
I have found another issue which I do not know how to fix. I selected few thousands of syllables on my sound files but later decided to rearange part of them. However when I go to Unit Table, Exemplars or select syllables at the Ordination graph I still see the old version of these selections. First I waited few days and see whether a problem will fix itself (it worked with another issue in KOE :)). Then I tried to clear my browser catche, cookies and reset settings as well as create a new database where I loaded the wav and selection files (even changed selection lable names). They still show the old spectrograms.

Any ideas how to solve this issue? It is realy annoying since it unables me to classify syllables.

Best wishes,
KD

**Comment by BirdGuyWes** [comment]
We believe we have now resolved this issue! If not, please let us know.

**Comment by Dumetorum** [comment]
It looks that everything is ok. Thank you! : )
